// AUTO-GENERATED by scripts/generate-endpoints.mjs — do not edit by hand.
// Source: https://api.magileads.net/swagger.json
// Non-admin Magileads API operations the generic passthrough tools may call.
// 367 operations (103 read, 264 write).

export type EndpointDef = { method: string; path: string; tag: string; summary: string; write: boolean };

export const NON_ADMIN_ENDPOINTS: EndpointDef[] = [
  {
    "method": "GET",
    "path": "/ai-agents",
    "tag": "AiAgents",
    "summary": "Fetch AI agents",
    "write": false
  },
  {
    "method": "POST",
    "path": "/ai-agents",
    "tag": "AiAgents",
    "summary": "Create AI agent",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/ai-agents/{uniqid}",
    "tag": "AiAgents",
    "summary": "Delete AI agent",
    "write": true
  },
  {
    "method": "GET",
    "path": "/ai-agents/{uniqid}",
    "tag": "AiAgents",
    "summary": "Find AI agent by uniqid",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/ai-agents/{uniqid}",
    "tag": "AiAgents",
    "summary": "Update AI agent",
    "write": true
  },
  {
    "method": "POST",
    "path": "/ai-agents/{uniqid}/generate-brief",
    "tag": "AiAgents",
    "summary": "Generate AI agent brief",
    "write": true
  },
  {
    "method": "POST",
    "path": "/ai-agents/generate-brief",
    "tag": "AiAgents",
    "summary": "Generate AI agent brief without an existing agent",
    "write": true
  },
  {
    "method": "GET",
    "path": "/api",
    "tag": "API",
    "summary": "Api information",
    "write": false
  },
  {
    "method": "GET",
    "path": "/api/{saas_domain}",
    "tag": "API",
    "summary": "Api information",
    "write": false
  },
  {
    "method": "GET",
    "path": "/blacklists",
    "tag": "Blacklists",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/blacklists",
    "tag": "Blacklists",
    "summary": "Create a blacklist",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/blacklists/{blacklist_id}",
    "tag": "Blacklists",
    "summary": "Delete a blacklist",
    "write": true
  },
  {
    "method": "GET",
    "path": "/blacklists/{blacklist_id}",
    "tag": "Blacklists",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/blacklists/{blacklist_id}",
    "tag": "Blacklists",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "GET",
    "path": "/blacklists/{blacklist_id}/data",
    "tag": "Blacklists",
    "summary": "Fetch data",
    "write": false
  },
  {
    "method": "POST",
    "path": "/blacklists/{blacklist_id}/data",
    "tag": "Blacklists",
    "summary": "Import data",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/blacklists/{blacklist_id}/data/{data_id}",
    "tag": "Blacklists",
    "summary": "Delete Data",
    "write": true
  },
  {
    "method": "POST",
    "path": "/blacklists/{blacklist_id}/data/search",
    "tag": "Blacklists",
    "summary": "Search data in specific blacklist",
    "write": true
  },
  {
    "method": "GET",
    "path": "/blacklists/{blacklist_id}/download/{file_type}",
    "tag": "Blacklists",
    "summary": "Download the blacklist",
    "write": false
  },
  {
    "method": "POST",
    "path": "/blacklists/{blacklist_id}/download/{file_type}",
    "tag": "Blacklists",
    "summary": "Download the blacklist using a filter",
    "write": true
  },
  {
    "method": "POST",
    "path": "/blacklists/data/search",
    "tag": "Blacklists",
    "summary": "Search data in all blacklist",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/blacklists/datas",
    "tag": "Blacklists",
    "summary": "Delete Datas",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists",
    "tag": "Contact Lists",
    "summary": "Fetch all lists",
    "write": false
  },
  {
    "method": "POST",
    "path": "/contact-lists",
    "tag": "Contact Lists",
    "summary": "Create a contact list",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists-paginated",
    "tag": "Contact Lists",
    "summary": "Fetch paginated list",
    "write": false
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}",
    "tag": "Contact Lists",
    "summary": "Delete a contact list",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists/{contact_list_id}",
    "tag": "Contact Lists",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/contact-lists/{contact_list_id}",
    "tag": "Contact Lists",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/contact",
    "tag": "Contact Lists",
    "summary": "Import contact",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}/contacts",
    "tag": "Contact Lists",
    "summary": "Delete contacts from a contact list",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists/{contact_list_id}/contacts",
    "tag": "Contact Lists",
    "summary": "Fetch contacts",
    "write": false
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/contacts",
    "tag": "Contact Lists",
    "summary": "Import contacts",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}/contacts/{contact_id}",
    "tag": "Contact Lists",
    "summary": "Delete Contact",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists/{contact_list_id}/contacts/{contact_id}",
    "tag": "Contact Lists",
    "summary": "Find contact profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/contact-lists/{contact_list_id}/contacts/{contact_id}",
    "tag": "Contact Lists",
    "summary": "Update contact",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/contacts/{contact_id}/enrich/phone/mobile",
    "tag": "Contact Lists",
    "summary": "Enrich a contact phone number",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}/contacts/blacklist/{blacklist_id}",
    "tag": "Contact Lists",
    "summary": "Delete contacts from a contact list found in a blacklist",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}/contacts/contact-list/{source_contact_list_id}",
    "tag": "Contact Lists",
    "summary": "Delete contacts from a contact list found in another contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/contacts/search",
    "tag": "Contact Lists",
    "summary": "Search contacts in specific contact list",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}/contacts/unsubscribers",
    "tag": "Contact Lists",
    "summary": "Delete contacts from a contact list found in unsubscribers",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}/contacts/unsubscribers/{organization_id}",
    "tag": "Contact Lists",
    "summary": "Delete contacts from a contact list found in unsubscribers from an organization",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/convert/linkedin/links",
    "tag": "Contact Lists",
    "summary": "Convert LinkedIn AC links to IN",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/copy",
    "tag": "Contact Lists",
    "summary": "Copy a contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/copy/blacklist/{blacklist_id}",
    "tag": "Contact Lists",
    "summary": "Copy a contact list to a blacklist",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/copy/prm",
    "tag": "Contact Lists",
    "summary": "Copy contact list to my prm",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/copy/to/{user_id}",
    "tag": "Contact Lists",
    "summary": "Copy a contact list to user ID",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/copy/unsubscribers",
    "tag": "Contact Lists",
    "summary": "Copy a contact list to unsubscribers",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/datafield-ai/{datafield_id}",
    "tag": "Contact Lists",
    "summary": "Generate dynamic content using AI from a contact list datafield",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/datafield-enrich/{datafield_id}",
    "tag": "Contact Lists",
    "summary": "Filling the datafield with AI",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/contact-lists/{contact_list_id}/datafields/{datafield_id}/bulk-set",
    "tag": "Contact Lists",
    "summary": "Bulk set datafield value",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists/{contact_list_id}/datafields/{datafield_id}/values",
    "tag": "Contact Lists",
    "summary": "Get unique values from a datafield",
    "write": false
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/{contact_list_id}/delete/company/{keep_contacts}",
    "tag": "Contact Lists",
    "summary": "Delete contacts on a contact list to keep only a certain amount of contacts by company",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists/{contact_list_id}/download/{file_type}",
    "tag": "Contact Lists",
    "summary": "Download the list of contacts",
    "write": false
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/download/{file_type}",
    "tag": "Contact Lists",
    "summary": "Download the list of contacts using a filter",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/email-verifier",
    "tag": "Contact Lists",
    "summary": "Verify emails in a contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/enrich",
    "tag": "Contact Lists",
    "summary": "Enrich a contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/enrich/external/{enrich_external_api}/{external_api_key_id}",
    "tag": "Contact Lists",
    "summary": "Enrich a contact list using an external api",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/enrich/linkedin",
    "tag": "Contact Lists",
    "summary": "Enrich a contact list with LinkedIn data",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/enrich/linkedin/url",
    "tag": "Contact Lists",
    "summary": "Enrich LinkedIn URLs",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/enrich/phone/mobile",
    "tag": "Contact Lists",
    "summary": "Enrich the phone number of multiple contacts",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/icebreaker",
    "tag": "Contact Lists",
    "summary": "Generate an Ice Breaker of list contacts",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/split",
    "tag": "Contact Lists",
    "summary": "Split a contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/{contact_list_id}/translate",
    "tag": "Contact Lists",
    "summary": "Translate a contact list",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/contacts",
    "tag": "Contact Lists",
    "summary": "Delete Contacts",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/contacts/copy/{contact_list_id_destination}",
    "tag": "Contact Lists",
    "summary": "Copy contacts from all contact lists to a contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/contacts/copy/prm",
    "tag": "Contact Lists",
    "summary": "Copy contacts to my prm",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/contacts/copy/to/{contact_list_id_destination}",
    "tag": "Contact Lists",
    "summary": "Copy contacts from one list to another",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/contacts/search",
    "tag": "Contact Lists",
    "summary": "Search contacts in all contact list",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/contact-lists/contacts/selection",
    "tag": "Contact Lists",
    "summary": "Delete Contacts from a selection",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/download/{file_type}",
    "tag": "Contact Lists",
    "summary": "Download the list of contacts from all contacts lists",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contact-lists/merge",
    "tag": "Contact Lists",
    "summary": "Merge contact lists",
    "write": true
  },
  {
    "method": "GET",
    "path": "/contact-lists/names",
    "tag": "Contact Lists",
    "summary": "Fetch contact list IDs and names",
    "write": false
  },
  {
    "method": "POST",
    "path": "/contacts/enrich/email",
    "tag": "Contact Lists",
    "summary": "Enrich a contact email from company and optional names",
    "write": true
  },
  {
    "method": "POST",
    "path": "/contacts/enrich/phone/mobile",
    "tag": "Contact Lists",
    "summary": "Enrich a contact mobile phone from LinkedIn URL",
    "write": true
  },
  {
    "method": "GET",
    "path": "/data-fields",
    "tag": "Data Fields",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/data-fields",
    "tag": "Data Fields",
    "summary": "Create a data field",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/data-fields/{data_field_id}",
    "tag": "Data Fields",
    "summary": "Delete a data field",
    "write": true
  },
  {
    "method": "GET",
    "path": "/data-fields/{data_field_id}",
    "tag": "Data Fields",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/data-fields/{data_field_id}",
    "tag": "Data Fields",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "GET",
    "path": "/email-signatures",
    "tag": "Email Signatures",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/email-signatures",
    "tag": "Email Signatures",
    "summary": "Create an email signature",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/email-signatures/{email_signature_id}",
    "tag": "Email Signatures",
    "summary": "Delete an email signature",
    "write": true
  },
  {
    "method": "GET",
    "path": "/email-signatures/{email_signature_id}",
    "tag": "Email Signatures",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/email-signatures/{email_signature_id}",
    "tag": "Email Signatures",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "POST",
    "path": "/email-signatures/{email_signature_id}/copy",
    "tag": "Email Signatures",
    "summary": "Copy an email signature",
    "write": true
  },
  {
    "method": "POST",
    "path": "/enrich",
    "tag": "Enrich",
    "summary": "Create an enrich batch",
    "write": true
  },
  {
    "method": "GET",
    "path": "/enrich/{batch_id}",
    "tag": "Enrich",
    "summary": "Get enrich batch results",
    "write": false
  },
  {
    "method": "POST",
    "path": "/enrich/usage",
    "tag": "Enrich",
    "summary": "Get enrich usage statistics",
    "write": true
  },
  {
    "method": "GET",
    "path": "/files",
    "tag": "Files",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/files",
    "tag": "Files",
    "summary": "Upload a file",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/files/{file_id}",
    "tag": "Files",
    "summary": "Delete a file",
    "write": true
  },
  {
    "method": "GET",
    "path": "/files/{file_id}",
    "tag": "Files",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "POST",
    "path": "/files/{file_id}",
    "tag": "Files",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "POST",
    "path": "/files/search",
    "tag": "Files",
    "summary": "Search files",
    "write": true
  },
  {
    "method": "GET",
    "path": "/folders",
    "tag": "Folders",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/folders",
    "tag": "Folders",
    "summary": "Create a folder",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/folders/{folder_id}",
    "tag": "Folders",
    "summary": "Delete a folder",
    "write": true
  },
  {
    "method": "GET",
    "path": "/folders/{folder_id}",
    "tag": "Folders",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/folders/{folder_id}",
    "tag": "Folders",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "GET",
    "path": "/forms",
    "tag": "Forms",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/forms",
    "tag": "Forms",
    "summary": "Create a form",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/forms/{form_id}",
    "tag": "Forms",
    "summary": "Delete a form",
    "write": true
  },
  {
    "method": "GET",
    "path": "/forms/{form_id}",
    "tag": "Forms",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/forms/{form_id}",
    "tag": "Forms",
    "summary": "Update a form profile",
    "write": true
  },
  {
    "method": "POST",
    "path": "/forms/{form_id}/copy",
    "tag": "Forms",
    "summary": "Copy a form",
    "write": true
  },
  {
    "method": "GET",
    "path": "/integrations/email",
    "tag": "Integrations - Email",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "DELETE",
    "path": "/integrations/email/{email_account_id}",
    "tag": "Integrations - Email",
    "summary": "Delete an email account",
    "write": true
  },
  {
    "method": "GET",
    "path": "/integrations/email/{email_account_id}",
    "tag": "Integrations - Email",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "GET",
    "path": "/integrations/email/discover/{email}",
    "tag": "Integrations - Email",
    "summary": "Discover email server settings using Autodiscover",
    "write": false
  },
  {
    "method": "POST",
    "path": "/integrations/email/gmail",
    "tag": "Integrations - Email",
    "summary": "Add a Gmail email account",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/integrations/email/gmail/{email_account_id}",
    "tag": "Integrations - Email",
    "summary": "Update a Gmail email account",
    "write": true
  },
  {
    "method": "POST",
    "path": "/integrations/email/mass-mailing",
    "tag": "Integrations - Email",
    "summary": "Add an email account for mass mailing",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/integrations/email/mass-mailing/{email_account_id}",
    "tag": "Integrations - Email",
    "summary": "Update an email account for mass mailing",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/integrations/email/mass-mailing/{email_account_id}/force/validate",
    "tag": "Integrations - Email",
    "summary": "Force Mass Mailing email validation",
    "write": true
  },
  {
    "method": "POST",
    "path": "/integrations/email/outlook",
    "tag": "Integrations - Email",
    "summary": "Add a Outlook email account",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/integrations/email/outlook/{email_account_id}",
    "tag": "Integrations - Email",
    "summary": "Update a Outlook email account",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/integrations/email/protection/{protection_id}",
    "tag": "Integrations - Email",
    "summary": "Set a protection as handled",
    "write": true
  },
  {
    "method": "GET",
    "path": "/integrations/email/protections",
    "tag": "Integrations - Email",
    "summary": "List the anti spam protections you have received by email",
    "write": false
  },
  {
    "method": "POST",
    "path": "/integrations/email/smtp",
    "tag": "Integrations - Email",
    "summary": "Add a SMTP email account",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/integrations/email/smtp/{email_account_id}",
    "tag": "Integrations - Email",
    "summary": "Update a SMTP email account",
    "write": true
  },
  {
    "method": "GET",
    "path": "/integrations/email/smtp/{email_account_id}/warmup",
    "tag": "Integrations - Email",
    "summary": "Retrieve warmup settings for an SMTP email account",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/integrations/email/smtp/{email_account_id}/warmup",
    "tag": "Integrations - Email",
    "summary": "Update warmup settings for an SMTP email account",
    "write": true
  },
  {
    "method": "GET",
    "path": "/integrations/email/smtp/{email_account_id}/warmup/stats",
    "tag": "Integrations - Email",
    "summary": "Retrieve warmup statistics for an SMTP email account.",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/integrations/email/smtp/validity/test",
    "tag": "Integrations - Email",
    "summary": "SMTP email accounts validity test",
    "write": true
  },
  {
    "method": "GET",
    "path": "/integrations/linkedin",
    "tag": "Integrations - LinkedIn",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/integrations/linkedin",
    "tag": "Integrations - LinkedIn",
    "summary": "Add a LinkedIn account",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/integrations/linkedin/{linkedin_account_id}",
    "tag": "Integrations - LinkedIn",
    "summary": "Delete a LinkedIn account",
    "write": true
  },
  {
    "method": "GET",
    "path": "/integrations/linkedin/{linkedin_account_id}",
    "tag": "Integrations - LinkedIn",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/integrations/linkedin/{linkedin_account_id}",
    "tag": "Integrations - LinkedIn",
    "summary": "Update a LinkedIn account",
    "write": true
  },
  {
    "method": "POST",
    "path": "/integrations/linkedin/{linkedin_account_id}/checkpoint",
    "tag": "Integrations - LinkedIn",
    "summary": "Solve an authentication checkpoint using a code that you received. If the checkpoint is via the app, you can enter any code you want once va",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/jobs/{job_uniqid}",
    "tag": "Jobs",
    "summary": "Stop a job",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/jobs/failed/{job_uniqid}",
    "tag": "Jobs",
    "summary": "Delete failed job result",
    "write": true
  },
  {
    "method": "GET",
    "path": "/jobs/prm/{target_id}",
    "tag": "Jobs",
    "summary": "List prm jobs",
    "write": false
  },
  {
    "method": "GET",
    "path": "/models/email",
    "tag": "Models - Email",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/email",
    "tag": "Models - Email",
    "summary": "Create an email model",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/models/email/{model_id}",
    "tag": "Models - Email",
    "summary": "Delete an email model",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/email/{model_id}",
    "tag": "Models - Email",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/models/email/{model_id}",
    "tag": "Models - Email",
    "summary": "Update an email model",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/email/{model_id}/{contact_id}",
    "tag": "Models - Email",
    "summary": "Find AI model profile and generate content",
    "write": false
  },
  {
    "method": "GET",
    "path": "/models/email/{model_id}/{contact_id}/regenerate",
    "tag": "Models - Email",
    "summary": "Find AI model profile and regenerate content",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/email/{model_id}/copy",
    "tag": "Models - Email",
    "summary": "Copy an email model",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/email/{model_id}/copy/to/{user_id}",
    "tag": "Models - Email",
    "summary": "Copy an email model to user ID",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/email/{model_id}/regenerate",
    "tag": "Models - Email",
    "summary": "Regenerate an email model using AI",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/email/{model_id}/send/test",
    "tag": "Models - Email",
    "summary": "Send an email campaign on your test emails",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/email/generate",
    "tag": "Models - Email",
    "summary": "Generate an email model using AI",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/email/generate/html",
    "tag": "Models - Email",
    "summary": "Generate HTML email using AI",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/email/get/html/from/url",
    "tag": "Models - Email",
    "summary": "Get HTML from URL",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/email/send/test",
    "tag": "Models - Email",
    "summary": "Send an email campaign on your test emails without creating a model",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/linkedin/invitation",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/linkedin/invitation",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Create a LinkedIn invitation",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/models/linkedin/invitation/{model_id}",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Delete a LinkedIn invitation",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/linkedin/invitation/{model_id}",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/models/linkedin/invitation/{model_id}",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Update a LinkedIn invitation",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/linkedin/invitation/{model_id}/{contact_id}",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Find AI model profile and generate content",
    "write": false
  },
  {
    "method": "GET",
    "path": "/models/linkedin/invitation/{model_id}/{contact_id}/regenerate",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Find AI model profile and regenerate content",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/linkedin/invitation/{model_id}/copy",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Copy a LinkedIn invitation",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/linkedin/invitation/{model_id}/copy/to/{user_id}",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Copy a LinkedIn invitation to user ID",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/linkedin/invitation/generate/content",
    "tag": "Models - LinkedIn Invitation",
    "summary": "Generate LinkedIn invitation content using AI",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/linkedin/message",
    "tag": "Models - LinkedIn Message",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/linkedin/message",
    "tag": "Models - LinkedIn Message",
    "summary": "Create a LinkedIn message",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/models/linkedin/message/{model_id}",
    "tag": "Models - LinkedIn Message",
    "summary": "Delete a LinkedIn message",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/linkedin/message/{model_id}",
    "tag": "Models - LinkedIn Message",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/models/linkedin/message/{model_id}",
    "tag": "Models - LinkedIn Message",
    "summary": "Update a LinkedIn message",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/linkedin/message/{model_id}/{contact_id}",
    "tag": "Models - LinkedIn Message",
    "summary": "Find AI model profile and generate content",
    "write": false
  },
  {
    "method": "GET",
    "path": "/models/linkedin/message/{model_id}/{contact_id}/regenerate",
    "tag": "Models - LinkedIn Message",
    "summary": "Find AI model profile and regenerate content",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/linkedin/message/{model_id}/copy",
    "tag": "Models - LinkedIn Message",
    "summary": "Copy a LinkedIn message",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/linkedin/message/{model_id}/copy/to/{user_id}",
    "tag": "Models - LinkedIn Message",
    "summary": "Copy a LinkedIn message to user ID",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/linkedin/message/generate/content",
    "tag": "Models - LinkedIn Message",
    "summary": "Generate LinkedIn message content using AI",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/sms",
    "tag": "Models - SMS",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/sms",
    "tag": "Models - SMS",
    "summary": "Create a SMS model",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/models/sms/{model_id}",
    "tag": "Models - SMS",
    "summary": "Delete a SMS model",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/sms/{model_id}",
    "tag": "Models - SMS",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/models/sms/{model_id}",
    "tag": "Models - SMS",
    "summary": "Update a SMS model",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/sms/{model_id}/copy",
    "tag": "Models - SMS",
    "summary": "Copy a SMS model",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/sms/{model_id}/copy/to/{user_id}",
    "tag": "Models - SMS",
    "summary": "Copy a SMS model to user ID",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/smv",
    "tag": "Models - SMV",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/smv",
    "tag": "Models - SMV",
    "summary": "Create a SMV model",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/models/smv/{model_id}",
    "tag": "Models - SMV",
    "summary": "Delete a SMV model",
    "write": true
  },
  {
    "method": "GET",
    "path": "/models/smv/{model_id}",
    "tag": "Models - SMV",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "POST",
    "path": "/models/smv/{model_id}",
    "tag": "Models - SMV",
    "summary": "Update a SMV model",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/smv/{model_id}/copy",
    "tag": "Models - SMV",
    "summary": "Copy a SMV model",
    "write": true
  },
  {
    "method": "POST",
    "path": "/models/smv/{model_id}/copy/to/{user_id}",
    "tag": "Models - SMV",
    "summary": "Copy a SMV model to user ID",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/contact/{contact_id}",
    "tag": "PRM",
    "summary": "Find a contact profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/prm/contact/{contact_id}",
    "tag": "PRM",
    "summary": "Update a PRM contact",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/call",
    "tag": "PRM",
    "summary": "Create a PRM call from a contact",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/contact/{contact_id}/call/{call_id}",
    "tag": "PRM",
    "summary": "Delete a PRM call from a contact",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/enrich/phone/mobile",
    "tag": "PRM",
    "summary": "Enrich a contact phone number",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/exclude/{workflow_id}",
    "tag": "PRM",
    "summary": "Exclude a PRM contact from a workflow",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/exclude/programmation/{programmation_id}",
    "tag": "PRM",
    "summary": "Exclude a PRM contact from a programmation",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/linkedin/invitation",
    "tag": "PRM",
    "summary": "Send a linkedin invitation to a contact",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/linkedin/message",
    "tag": "PRM",
    "summary": "Send a linkedin message to a contact",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/note",
    "tag": "PRM",
    "summary": "Create a PRM note from a contact",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/contact/{contact_id}/note/{note_id}",
    "tag": "PRM",
    "summary": "Delete a PRM note from a contact",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/prm/contact/{contact_id}/note/{note_id}",
    "tag": "PRM",
    "summary": "Update a PRM note from a contact",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/note/{note_id}/attachment",
    "tag": "PRM",
    "summary": "Upload note attachments",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/contact/{contact_id}/note/{note_id}/attachment/{attachment_id}",
    "tag": "PRM",
    "summary": "Delete note attachment",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/contact/{contact_id}/note/{note_id}/attachments",
    "tag": "PRM",
    "summary": "Get note attachments",
    "write": false
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/programmation/{programmation_id}/step/{step_id}",
    "tag": "PRM",
    "summary": "Manually progress a contact to an event after a call step",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/prm/contact/{contact_id}/reply/{history_type_reply}/{reply_id}",
    "tag": "PRM",
    "summary": "Mark a contact reply as positive/negative or remove the mark",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contact/{contact_id}/reply/{history_type_reply}/{reply_id}/suggest-reply",
    "tag": "PRM",
    "summary": "Generate a suggested reply using AI",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/contacts",
    "tag": "PRM",
    "summary": "Delete contacts from your PRM",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/contacts",
    "tag": "PRM",
    "summary": "Fetch the contacts of your PRM",
    "write": false
  },
  {
    "method": "POST",
    "path": "/prm/contacts",
    "tag": "PRM",
    "summary": "Import contact into your PRM",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/contact-list/{contact_list_id}/add",
    "tag": "PRM",
    "summary": "Add contacts from a PRM to a contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/enrich/external/{enrich_external_api}/{external_api_key_id}",
    "tag": "PRM",
    "summary": "Enrich the prm using an external api",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/export/{file_type}",
    "tag": "PRM",
    "summary": "Export the contacts of your PRM",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/import",
    "tag": "PRM",
    "summary": "Import contacts",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/prm/contacts/new_reply",
    "tag": "PRM",
    "summary": "Update PRM contacts new reply",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/contacts/shared",
    "tag": "PRM",
    "summary": "Fetch the contacts of your PRM that you shared",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/prm/contacts/status",
    "tag": "PRM",
    "summary": "Update PRM contacts statuses",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/contacts/user/{user_id}",
    "tag": "PRM",
    "summary": "Delete contacts from a PRM",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/contacts/user/{user_id}",
    "tag": "PRM",
    "summary": "Fetch contacts of a PRM",
    "write": false
  },
  {
    "method": "POST",
    "path": "/prm/contacts/user/{user_id}",
    "tag": "PRM",
    "summary": "Import contact into a PRM",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/user/{user_id}/copy/blacklist/{blacklist_id}",
    "tag": "PRM",
    "summary": "Copy PRM contacts to a blacklist",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/user/{user_id}/enrich/external/{enrich_external_api}/{external_api_key_id}",
    "tag": "PRM",
    "summary": "Enrich the prm using an external api",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/user/{user_id}/export/{file_type}",
    "tag": "PRM",
    "summary": "Export contacts of a PRM",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/contacts/user/{user_id}/tags",
    "tag": "PRM",
    "summary": "Remove tags from contacts of a PRM",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/contacts/user/{user_id}/tags",
    "tag": "PRM",
    "summary": "Add tags to contacts of a PRM",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/contacts/users",
    "tag": "PRM",
    "summary": "Fetch contacts of multiple PRM",
    "write": false
  },
  {
    "method": "GET",
    "path": "/prm/list",
    "tag": "PRM",
    "summary": "List visible PRM",
    "write": false
  },
  {
    "method": "GET",
    "path": "/prm/notifications/column-entry",
    "tag": "PRM",
    "summary": "Retrieve PRM column-entry notification watchlist",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/prm/notifications/column-entry",
    "tag": "PRM",
    "summary": "Replace PRM column-entry notification watchlist",
    "write": true
  },
  {
    "method": "POST",
    "path": "/prm/nurturing",
    "tag": "PRM",
    "summary": "Create a PRM nurturing",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/nurturing/{nurturing_id}",
    "tag": "PRM",
    "summary": "Delete a PRM nurturing",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/nurturing/{nurturing_id}",
    "tag": "PRM",
    "summary": "Get a PRM nurturing",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/prm/nurturing/{nurturing_id}",
    "tag": "PRM",
    "summary": "Update a PRM nurturing",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/nurturings",
    "tag": "PRM",
    "summary": "Get PRM nurturings",
    "write": false
  },
  {
    "method": "GET",
    "path": "/prm/sharings",
    "tag": "PRM",
    "summary": "Retrieve your PRM sharings",
    "write": false
  },
  {
    "method": "POST",
    "path": "/prm/sharings",
    "tag": "PRM",
    "summary": "Create sharing",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/sharings/{sharing_id}",
    "tag": "PRM",
    "summary": "Delete sharing",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/prm/sharings/{sharing_id}",
    "tag": "PRM",
    "summary": "Update sharing",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/status",
    "tag": "PRM",
    "summary": "Retrieve your PRM statuses",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/prm/status/{status}",
    "tag": "PRM",
    "summary": "Update a PRM status",
    "write": true
  },
  {
    "method": "GET",
    "path": "/prm/status/custom",
    "tag": "PRM",
    "summary": "Retrieve your PRM custom statuses",
    "write": false
  },
  {
    "method": "POST",
    "path": "/prm/status/custom",
    "tag": "PRM",
    "summary": "Create a PRM custom status",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/prm/status/custom/{status_id}",
    "tag": "PRM",
    "summary": "Delete a PRM custom status",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/prm/status/custom/{status_id}",
    "tag": "PRM",
    "summary": "Update a PRM custom status",
    "write": true
  },
  {
    "method": "POST",
    "path": "/reporting/report",
    "tag": "Reporting",
    "summary": "Create a report",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/reporting/report/{report_id}",
    "tag": "Reporting",
    "summary": "Delete a report",
    "write": true
  },
  {
    "method": "GET",
    "path": "/reporting/report/{report_id}",
    "tag": "Reporting",
    "summary": "Retrieve a report",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/reporting/report/{report_id}",
    "tag": "Reporting",
    "summary": "Update report",
    "write": true
  },
  {
    "method": "GET",
    "path": "/reporting/reports",
    "tag": "Reporting",
    "summary": "Fetch list of reports",
    "write": false
  },
  {
    "method": "DELETE",
    "path": "/resellers/{reseller_id}/mailgun",
    "tag": "Resellers - Mailgun",
    "summary": "Delete the reseller Mailgun configuration",
    "write": true
  },
  {
    "method": "GET",
    "path": "/resellers/{reseller_id}/mailgun",
    "tag": "Resellers - Mailgun",
    "summary": "Retrieve the reseller Mailgun configuration",
    "write": false
  },
  {
    "method": "POST",
    "path": "/resellers/{reseller_id}/mailgun",
    "tag": "Resellers - Mailgun",
    "summary": "Configure reseller-managed Mailgun",
    "write": true
  },
  {
    "method": "POST",
    "path": "/resellers/{reseller_id}/mailgun/domain-imports",
    "tag": "Resellers - Mailgun",
    "summary": "Import an existing Mailgun domain",
    "write": true
  },
  {
    "method": "GET",
    "path": "/resellers/{reseller_id}/mailgun/domains",
    "tag": "Resellers - Mailgun",
    "summary": "List visible reseller-managed Mailgun domains",
    "write": false
  },
  {
    "method": "POST",
    "path": "/resellers/{reseller_id}/mailgun/domains",
    "tag": "Resellers - Mailgun",
    "summary": "Create a reseller-managed Mailgun domain",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/resellers/{reseller_id}/mailgun/domains/{domain_id}",
    "tag": "Resellers - Mailgun",
    "summary": "Delete or detach a managed Mailgun domain",
    "write": true
  },
  {
    "method": "GET",
    "path": "/resellers/{reseller_id}/mailgun/domains/{domain_id}",
    "tag": "Resellers - Mailgun",
    "summary": "Retrieve a reseller-managed Mailgun domain",
    "write": false
  },
  {
    "method": "POST",
    "path": "/resellers/{reseller_id}/mailgun/domains/{domain_id}",
    "tag": "Resellers - Mailgun",
    "summary": "Update managed Mailgun domain sharing",
    "write": true
  },
  {
    "method": "POST",
    "path": "/resellers/{reseller_id}/mailgun/domains/{domain_id}/dns-refresh-requests",
    "tag": "Resellers - Mailgun",
    "summary": "Refresh managed Mailgun DNS verification",
    "write": true
  },
  {
    "method": "GET",
    "path": "/resellers/{reseller_id}/mailgun/statistics",
    "tag": "Resellers - Mailgun",
    "summary": "Retrieve current-month managed Mailgun statistics",
    "write": false
  },
  {
    "method": "POST",
    "path": "/statistics/date",
    "tag": "Statistics",
    "summary": "Fetch programmation stats by date",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/date/contacts",
    "tag": "Statistics",
    "summary": "Download programmation contacts by date",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/date/detailed",
    "tag": "Statistics",
    "summary": "Fetch programmation stats by various parameters, day by day",
    "write": true
  },
  {
    "method": "GET",
    "path": "/statistics/global",
    "tag": "Statistics",
    "summary": "Fetch global programmations statistics",
    "write": false
  },
  {
    "method": "POST",
    "path": "/statistics/global/detailed",
    "tag": "Statistics",
    "summary": "Fetch global programmation stats by various parameters",
    "write": true
  },
  {
    "method": "GET",
    "path": "/statistics/integrations",
    "tag": "Statistics",
    "summary": "Fetch integrations statistics",
    "write": false
  },
  {
    "method": "GET",
    "path": "/statistics/messages",
    "tag": "Statistics",
    "summary": "Retrieve the list of possible statistics messages",
    "write": false
  },
  {
    "method": "GET",
    "path": "/statistics/programmations",
    "tag": "Statistics",
    "summary": "Fetch programmations statistics",
    "write": false
  },
  {
    "method": "GET",
    "path": "/statistics/programmations/{programmation_id}",
    "tag": "Statistics",
    "summary": "Fetch statistics of a programmation",
    "write": false
  },
  {
    "method": "GET",
    "path": "/statistics/programmations/{programmation_id}/download/{file_type}",
    "tag": "Statistics",
    "summary": "Download the statistics of a programmation",
    "write": false
  },
  {
    "method": "GET",
    "path": "/statistics/programmations/download/{file_type}",
    "tag": "Statistics",
    "summary": "Download programmations statistics",
    "write": false
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-channel-and-status",
    "tag": "Statistics",
    "summary": "Responders by channel and PRM status",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-company-size",
    "tag": "Statistics",
    "summary": "Responders by company size",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-company-size-and-status",
    "tag": "Statistics",
    "summary": "Responders by company size and PRM status",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-country",
    "tag": "Statistics",
    "summary": "Responders by country",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-prm-owner",
    "tag": "Statistics",
    "summary": "Responders by PRM contact owner",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-programmation-and-list",
    "tag": "Statistics",
    "summary": "Responders by programmation and contact list",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-region",
    "tag": "Statistics",
    "summary": "Responders by country and region",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-sector",
    "tag": "Statistics",
    "summary": "Responders by activity sector (top 10)",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-sector-and-status",
    "tag": "Statistics",
    "summary": "Responders by activity sector (top 10) and PRM status",
    "write": true
  },
  {
    "method": "POST",
    "path": "/statistics/responders/by-tag",
    "tag": "Statistics",
    "summary": "Responders by PRM contact tag",
    "write": true
  },
  {
    "method": "GET",
    "path": "/tags",
    "tag": "Tags",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/tags",
    "tag": "Tags",
    "summary": "Create a tag",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/tags/{tag_id}",
    "tag": "Tags",
    "summary": "Delete a tag",
    "write": true
  },
  {
    "method": "GET",
    "path": "/tags/{tag_id}",
    "tag": "Tags",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/tags/{tag_id}",
    "tag": "Tags",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/database/count",
    "tag": "Targeting - Database",
    "summary": "Count the number of contacts found with the given filters",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/database/count-preview",
    "tag": "Targeting - Database",
    "summary": "Count and preview contacts based on filters",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/database/extract",
    "tag": "Targeting - Database",
    "summary": "Extract contacts found with the given filters",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/database/locations/search",
    "tag": "Targeting - Database",
    "summary": "Search database location",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/google/extract-maps-search",
    "tag": "Targeting - Google",
    "summary": "Extract contacts from a Google Maps Search",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/google/extract-maps-search/{contact_list_id}/relaunch",
    "tag": "Targeting - Google",
    "summary": "Relaunch extractions",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/google/extract-maps-search/{contact_list_id}/relaunch-errors",
    "tag": "Targeting - Google",
    "summary": "Relaunch extractions with errors",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/google/generate-maps-search-urls",
    "tag": "Targeting - Google",
    "summary": "Generate Google Maps Search URLs",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/{contact_list_id}/relaunch-errors",
    "tag": "Targeting - LinkedIn",
    "summary": "Relaunch LinkedIn extractions with errors",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-companies-search-sync",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn companies from a company search (synchronous)",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-company-viewers",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn company viewers",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-connections",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract contacts from LinkedIn connections",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-event-attendees",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn event attendees",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-group-members",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn group members",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-people-comment-activity",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn people comment activity",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-people-post-activity",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn people post activity",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-people-reaction-activity",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn people reaction activity",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-peoples-search",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract contacts from a LinkedIn search",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-peoples-search-alternative",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract contacts from a LinkedIn search (alternative)",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-peoples-search-sync",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn profiles from a people search (synchronous)",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-post-commenters",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract contacts who commented on a LinkedIn post",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-post-likers",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract contacts who liked a post on LinkedIn",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-post-reposters",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn post reposters",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-posts",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract posts on LinkedIn",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-posts-sync",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn posts (synchronous)",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-profile-viewers",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract LinkedIn profile viewers",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-publishers-job-offers",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract the publishers of job offers on LinkedIn",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-sales-navigator-companies-search",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract companies from a Sales Navigator search",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-sales-navigator-companies-search-alternative",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract companies from a Sales Navigator search (alternative)",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-sales-navigator-peoples-search",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract contacts from a Sales Navigator search",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/extract-sales-navigator-peoples-search-alternative",
    "tag": "Targeting - LinkedIn",
    "summary": "Extract contacts from a Sales Navigator search (alternative)",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/generate-peoples-search-url",
    "tag": "Targeting - LinkedIn",
    "summary": "Generate a Linkedin peoples search url",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/generate-sales-navigator-peoples-search-url",
    "tag": "Targeting - LinkedIn",
    "summary": "Generate a Linkedin Sales Navigator peoples search url",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/locations/search",
    "tag": "Targeting - LinkedIn",
    "summary": "Search linkedin location ids",
    "write": true
  },
  {
    "method": "POST",
    "path": "/targeting/linkedin/refresh/{contact_list_id}",
    "tag": "Targeting - LinkedIn",
    "summary": "Refresh LinkedIn targeting on a contact list",
    "write": true
  },
  {
    "method": "GET",
    "path": "/unsubscribers",
    "tag": "Unsubscribers",
    "summary": "Fetch unsubscribers",
    "write": false
  },
  {
    "method": "POST",
    "path": "/unsubscribers",
    "tag": "Unsubscribers",
    "summary": "Import unsubscribers",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/unsubscribers/{unsubscriber_id}",
    "tag": "Unsubscribers",
    "summary": "Delete an unsubscriber",
    "write": true
  },
  {
    "method": "GET",
    "path": "/unsubscribers/download/{file_type}",
    "tag": "Unsubscribers",
    "summary": "Download the list of unsubscribers",
    "write": false
  },
  {
    "method": "GET",
    "path": "/unsubscribers/organization/{organization_id}",
    "tag": "Unsubscribers",
    "summary": "Retrieve unsubscribers from an organization",
    "write": false
  },
  {
    "method": "GET",
    "path": "/unsubscribers/organization/{organization_id}/download/{file_type}",
    "tag": "Unsubscribers",
    "summary": "Download the list of unsubscribers from an organization",
    "write": false
  },
  {
    "method": "POST",
    "path": "/unsubscribers/organization/{organization_id}/search",
    "tag": "Unsubscribers",
    "summary": "Search unsubscribers from specific organization",
    "write": true
  },
  {
    "method": "POST",
    "path": "/unsubscribers/search",
    "tag": "Unsubscribers",
    "summary": "Search unsubscribers from all organizations",
    "write": true
  },
  {
    "method": "GET",
    "path": "/urls-shortener",
    "tag": "URLs Shortener",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/urls-shortener",
    "tag": "URLs Shortener",
    "summary": "Create a shortened URL",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/urls-shortener/{shortened_url_id}",
    "tag": "URLs Shortener",
    "summary": "Delete a shortened URL",
    "write": true
  },
  {
    "method": "GET",
    "path": "/urls-shortener/{shortened_url_id}",
    "tag": "URLs Shortener",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/urls-shortener/{shortened_url_id}",
    "tag": "URLs Shortener",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "GET",
    "path": "/urls-shortener/{url_code}",
    "tag": "URLs Shortener",
    "summary": "Find URL by URL code",
    "write": false
  },
  {
    "method": "POST",
    "path": "/urls-shortener/bulk",
    "tag": "URLs Shortener",
    "summary": "Create shortened URLs in bulk",
    "write": true
  },
  {
    "method": "GET",
    "path": "/users/me",
    "tag": "Users",
    "summary": "Find my profile",
    "write": false
  },
  {
    "method": "GET",
    "path": "/users/me/quick",
    "tag": "Users",
    "summary": "Find my profile (quick version)",
    "write": false
  },
  {
    "method": "GET",
    "path": "/workflows",
    "tag": "Workflows",
    "summary": "Fetch list",
    "write": false
  },
  {
    "method": "POST",
    "path": "/workflows",
    "tag": "Workflows",
    "summary": "Create a workflow",
    "write": true
  },
  {
    "method": "DELETE",
    "path": "/workflows/{workflow_id}",
    "tag": "Workflows",
    "summary": "Delete a workflow",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/{workflow_id}",
    "tag": "Workflows",
    "summary": "Find profile",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}",
    "tag": "Workflows",
    "summary": "Update profile",
    "write": true
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/copy",
    "tag": "Workflows",
    "summary": "Copy a workflow",
    "write": true
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/copy/to/{user_id}",
    "tag": "Workflows",
    "summary": "Copy a workflow to user ID",
    "write": true
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/image",
    "tag": "Workflows",
    "summary": "Upload workflow image",
    "write": true
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/program",
    "tag": "Workflows",
    "summary": "Program a workflow",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}",
    "tag": "Workflows",
    "summary": "Find a workflow programmation",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}",
    "tag": "Workflows",
    "summary": "Update programmation profile",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/{contact_type}",
    "tag": "Workflows",
    "summary": "Get contacts by workflow programmation and type",
    "write": false
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/{contact_type}/{file_type}",
    "tag": "Workflows",
    "summary": "Download contacts by workflow programmation and type",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/archive",
    "tag": "Workflows",
    "summary": "Archive a workflow programmation",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/resume",
    "tag": "Workflows",
    "summary": "Resume a workflow programmation",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/step/{step_id}/{contact_type}",
    "tag": "Workflows",
    "summary": "Get contacts by workflow programmation step and type",
    "write": false
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/step/{step_id}/{contact_type}/{file_type}",
    "tag": "Workflows",
    "summary": "Download contacts by workflow programmation step and type",
    "write": true
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/step/{step_id}/{contact_type}/blacklist/{blacklist_id}",
    "tag": "Workflows",
    "summary": "Blacklist contacts by workflow programmation step and type",
    "write": true
  },
  {
    "method": "POST",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/step/{step_id}/{contact_type}/copy-to/{contact_list_id_destination}",
    "tag": "Workflows",
    "summary": "Copy contacts of a workflow programmation step and type to a contact list",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/step/{step_id}/click/link/{link_url}",
    "tag": "Workflows",
    "summary": "Get clicker contacts by workflow programmation step and type and link",
    "write": false
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/step/{step_id}/resume",
    "tag": "Workflows",
    "summary": "Resume a workflow programmation step",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/step/{step_id}/stop",
    "tag": "Workflows",
    "summary": "Stop a workflow programmation step",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/stop",
    "tag": "Workflows",
    "summary": "Stop a workflow programmation",
    "write": true
  },
  {
    "method": "PUT",
    "path": "/workflows/{workflow_id}/programmation/{workflow_programmation_id}/unarchive",
    "tag": "Workflows",
    "summary": "Unarchive a workflow programmation",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/{workflow_id}/programmations",
    "tag": "Workflows",
    "summary": "Fetch workflow programmations by workflow id",
    "write": false
  },
  {
    "method": "POST",
    "path": "/workflows/ai-agent",
    "tag": "Workflows",
    "summary": "Queue AI agent workflow draft generation",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/ai-agent/jobs",
    "tag": "Workflows",
    "summary": "Fetch AI agent workflow generation jobs",
    "write": false
  },
  {
    "method": "GET",
    "path": "/workflows/ai-agent/jobs/{job_uniqid}",
    "tag": "Workflows",
    "summary": "Fetch AI agent workflow generation status",
    "write": false
  },
  {
    "method": "DELETE",
    "path": "/workflows/exclude/programmation/{exclusion_id}",
    "tag": "Workflows",
    "summary": "Remove exclusion of a contact from a programmation",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/exclude/programmation/{programmation_id}",
    "tag": "Workflows",
    "summary": "List exclusions of contacts from a programmation",
    "write": false
  },
  {
    "method": "GET",
    "path": "/workflows/programmations",
    "tag": "Workflows",
    "summary": "Fetch workflow programmations",
    "write": false
  },
  {
    "method": "GET",
    "path": "/workflows/programmations/contacts",
    "tag": "Workflows",
    "summary": "Fetch workflow programmations contacts",
    "write": false
  },
  {
    "method": "GET",
    "path": "/workflows/reply/email/{reply_id}/download/eml",
    "tag": "Workflows",
    "summary": "Download the eml of an email reply",
    "write": false
  },
  {
    "method": "POST",
    "path": "/workflows/send/email",
    "tag": "Workflows",
    "summary": "Send a single email",
    "write": true
  },
  {
    "method": "POST",
    "path": "/workflows/send/email-with-attachments",
    "tag": "Workflows",
    "summary": "Send a single email with attachments",
    "write": true
  },
  {
    "method": "GET",
    "path": "/workflows/sent/email/{id}/download/eml",
    "tag": "Workflows",
    "summary": "Download the eml of an email manually sent",
    "write": false
  }
];
